# Generated by Django 3.1.6 on 2021-03-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameModel(
            old_name='images',
            new_name='image',
        ),
        migrations.RenameModel(
            old_name='prizes',
            new_name='prize',
        ),
    ]
